apiVersion: v1
kind: Service
metadata:
  name: public-lb
  annotations: 
    service.data.kubernetes.io/aws-load-balancer-type: nlb
    service.data.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: Loadbalancer
  selector:
    app: nginx
  ports:
    - protocols: 
      port: 80
      targetport: web 