apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Ayomi234/helm-argo-test.git
  password: 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
  username: Ayomi234